### PR TITLE
Reduced memory usage when parsing many long string

### PR DESCRIPTION
**Pull request by Jongsic**
### Test code
```js
 #!/usr/bin/env node

const BitcoinCore = require('bitcoin-core');

let conn = new BitcoinCore({
	host: 'localhost',
	port: 8332,
	network: 'mainnet',
	username: 'bitcoin',
	password: 'bitcoin'
});
		
let blockNum = 558355; // example

(async () => {
	let hash = await conn.getBlockHash(blockNum);

	let prev = Date.now();
	let ret = await conn.getBlockByHash(hash, {
		extension: 'json'
	});

	console.log(Date.now() - prev, process.memoryUsage().heapUsed);
})();
```

I Tested on my laptap

#### Before Output ( 5 times )

```
1660 264063048
1694 264984656
1708 264312088
1681 264337120
1691 265233768
```

#### After Output ( 5 times )

Faster(even include same network time) and about 1/10 memory usage
```
1298 29823136
1325 29790656
1316 29875392
1344 29941656
1298 29785832
```

### CODE REVIEW

**Comment by Jongsic** [comment]
Above failure seems not my fault.

'debug' library has syntax that fail on testing. 


In My laptap

```
> npm test 

  Testing bigint support
    ✓ Should show classic JSON.parse lacks bigint support
    ✓ Should show JSNbig does support bigint parse/stringify roundtrip

  Testing 'strict' option
    ✓ Should show that duplicate keys just get overwritten by default
    ✓ Should show that the 'strict' option will fail-fast on duplicate keys

  Testing 'storeAsString' option
    ✓ Should show that the key is of type object
    ✓ Should show that key is of type string, when storeAsString option is true


  6 passing (27ms)
```

**Comment by nickkolok** [comment]
@Jongsic , please consider cherry-picking https://github.com/sidorares/json-bigint/pull/30/commits/a6594d8ad0c0b6702914f9a46ddedb80b842bd39 and, optionally, 60f25be682432217aea1e4f6babf3c360d0b83a1 .
It should solve the problem with `debug` library

**Comment by todorone** [comment]
@sidorares Would You please consider to merge this PR as it improves speed/memory footprint for large data structures?

**Comment by babyadoresorange** [comment]
This improves speed, the PR needs to be rebased to merge ?

**Comment by sidorares** [comment]
merged as part of #36

**Pull request closed without merging**
