### PR TITLE
Native bigints support

### LINKED ISSUE #29: Why not use BigInt now native to node.js since v10.4.0?
Since v8 added navtive [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) support and that has been available since node.js v10.4.0, why not use that instead of bignumber.js?

Thanks for this package! Greate work!

### PR DESCRIPTION
**Pull request by nickkolok**
Possibly closes #29 

Hope that documentation for new features is good enough, otherwise please tell me what do you want :)

### CODE REVIEW

**Comment by nickkolok** [comment]
Sorry for multiple force-pushes... The problem was that the original `v0.3.0` failed to build on Travis: https://travis-ci.org/nickkolok/json-bigint/builds/500765245

**Comment by Almenon** [comment]
This will come in handy for vscode extension developers once vscode upgrades to 10.4.0 (currently on 10.2.0)

**Comment by jc-lab** [comment]
Why still this PR not merged or doesn't support native bigint?

**Comment by nickkolok** [comment]
@jc-lab , you may want to use this fork: https://github.com/Aisse-258/bigint-json-native

**Pull request closed without merging**
